config/routes.rb
Rails.application.routes.draw do
  devise_for :teachers
  devise_for :students
  resources :homes
  resources :absences
  resources :grades
  resources :classes
  resources :students
  resources :subjects
  resources :teachers
  resource :teacher_subjects


  root to: 'homes_#index'
  get "znamky/:stud_id", to: "students#show_all_grades"
  get "absencie/:stud_id", to: "students#show_all_absence"
  get "zapis_znamky/:teach_id", to: "teachers#show_teacher_grades", as: "znamky_ucitela"
  get "zapis_absencii/:teach_id", to: "teachers#show_all_absences", as: "vypis_absencii_ucitel"

  post "zapis_znamky/:teach_id", to: "teachers#add_grade"
  get "zapis_znamky/:teach_id/edit/:grade_id", to: "teachers#edit", as: "znamky_edit"
  post "zapis_absencii/:teach_id", to: "teachers#add_absence"
  get "zapis_absencii/:teach_id/edit/:abs_id", to: "teachers#edit_absence", as: "absencie_edit"
  delete "zapis_znamky/:teach_id", to: "grades#destroy"
  delete "zapis_absencii/:teach_id", to: "absences#destroy"
  delete "triedy/:teach_id", to: "classes#destroy"
  get "triedy/:teach_id", to: "teachers#all_classes", as: "vsetky_triedy"
  get "triedy/:teach_id/edit/:class_id", to: "teachers#edit_triedy", as: "class_edit"
  post "triedy/:teach_id", to: "teachers#add_classes"
  get "triedy/:teach_id/:class_id",  to:"teachers#class_detail", as: "class_detail"
  get "triedy/:teach_id/:class_id/edit/:stud_id", to:"teachers#edit_triedy_ziaka", as: "student_class_edit"
  get "ucitelia", to:"teachers#teachers_managment", as: "ucitelia_home"
  get "ucitelia/:id", to: "teachers#rozcestnik", as: "rozcestnik_pre_ucitelov"
  get "ucitelia/:id/predmety", to: "teachers#ucitel_predmety", as: "ucitel_predmety"
  get "ucitelia/:id/triedy", to: "teachers#ucitel_triedy", as: "ucitel_triedy"
  post "ucitelia/:id/predmety", to: "teachers#add_subject_teacher", as: "ucitel_add_triedy"
  get "vysvedcenie/:student_id/", to:"teachers#download_report"
  delete "ucitelia/:id/predmety", to: "teachers#destroy_teacher_subject"
  delete "ucitelia/:id/triedy", to: "teachers#destroy_teacher_classe"
  post "ucitelia/:id/triedy", to: "teachers#add_class_teacher"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/home.rb
class Home < ApplicationRecord
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    before_action :authenticate_student!, except: [ :index]
    before_action :authenticate_teacher!, except: [ :index]
#Priprava udajov pre grafy na landing page
  def index
    @pocet_ucitelov = Teacher.all.count
    @pocet_studentov = Student.all.count
    @pocet_jednotiek = Grade.all.where(value: 1).count
    @pocet_dvojok = Grade.all.where(value: 2).count
    @pocet_trojok = Grade.all.where(value: 3).count
    @pocet_stvoriek = Grade.all.where(value: 4).count
    @pocet_patiek = Grade.all.where(value: 5).count
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h3 class="color-red display-3">Vitajte v akademickom systéme.</h3>
    <p class="lead">Tento systém je určený na správu študijných informácií o študentoch.</p>
    <% if !((student_signed_in?) || (teacher_signed_in?)) %><h3 class="display-4">Čo v tomto systéme nájdete?</h3><% end %>
    <hr class="my-4">

    <% if !((student_signed_in?) || (teacher_signed_in?)) %>
    <p class="lead text-center">Pre učitela</p>
    <hr class="short">
    <div class="card-deck mb-3 text-center">
      <div class="card mb-4 box-shadow" data-aos="slide-right">
        <div class="card-header">
          <h4 class="my-0 font-weight-normal">Administrácia známok</h4>
        </div>
        <div class="card-body">
          <h1 class="card-title pricing-card-title"><i class="fas fa-book big"></i></h1>
          <ul class="list-unstyled mt-3 mb-4">
            <li>Pridávanie známok</li>
            <li>Úprava známok</li>
          </ul>
        </div>
      </div>
      <div class="card mb-4 box-shadow" data-aos="fade-down">
        <div class="card-header">
          <h4 class="my-0 font-weight-normal">Administrácia absencií</h4>
        </div>
        <div class="card-body">
          <h1 class="card-title pricing-card-title"><i class="fas fa-calendar-minus big"></i></h1>
          <ul class="list-unstyled mt-3 mb-4">
            <li>Jednoduchá administrácia absencií jednotlivých žiakov.</li>
          </ul>
        </div>
      </div>
      <div class="card mb-4 box-shadow" data-aos="slide-left">
        <div class="card-header">
          <h4 class="my-0 font-weight-normal">Manažment tried, učiteľov a predmetov</h4>
        </div>
        <div class="card-body">
          <h1 class="card-title pricing-card-title"><i class="fab fa-buromobelexperte big"></i></h1>
          <ul class="list-unstyled mt-3 mb-4">
            <li>Pridávanie žiakov do tried</li>
            <li>Priraďovanie predmetov k triedam</li>
          </ul>
        </div>
      </div>
    </div>

    <p class="lead text-center">Pre študenta</p>
    <hr class="short">
    <div class="card-deck mb-3 text-center">
      <div class="card mb-4 box-shadow" data-aos="slide-right">
        <div class="card-header">
          <h4 class="my-0 font-weight-normal">Informácie o známkach</h4>
        </div>
        <div class="card-body">
          <h1 class="card-title pricing-card-title"><i class="fas fa-book big"></i></h1>
          <ul class="list-unstyled mt-3 mb-4">
            <li>Prezrite si vaše doterajšie známky rýchlo a efektívne.</li>
          </ul>
        </div>
      </div>
      <div class="card mb-4 box-shadow" data-aos="slide-left">
        <div class="card-header">
          <h4 class="my-0 font-weight-normal">Informácie o absenciách</h4>
        </div>
        <div class="card-body">
          <h1 class="card-title pricing-card-title"><i class="fas fa-calendar-minus big"></i></h1>
          <ul class="list-unstyled mt-3 mb-4">
            <li>Kontrolovať, kedy ste nebol v škole prítomný/á nikdy nebolo také jednoduché!</li>
          </ul>
        </div>
      </div>
    </div>
    <% end %>


    <% if (teacher_signed_in?)  %>
    <div class="row">
      <div class="col-md-6 col-sm-12 mt-20" data-aos="fade-down">
        <a href="/zapis_znamky/<%= current_teacher.id %>">
          <div class="card">
            <div class="card-body">
              <div class="w-20 float-left">
                <i class="fas fa-book big"></i>
              </div>
              <div class="w-80 float-left">
                <h5 class="card-title"> Zápis známok</h5>
              </div>
              <div class="w-100">
                <p class="card-text">Kliknite na zapísanie známok študentom.</p>
              </div>
            </div>
          </div>
        </a>
      </div>
      <div class="col-md-6 col-sm-12 mt-20" data-aos="fade-down">
        <a href="/zapis_absencii/<%= current_teacher.id %>">
          <div class="card">
            <div class="card-body">
              <div class="w-20 float-left">
                <i class="fas fa-calendar-minus big"></i>
              </div>
              <div class="w-80 float-left">
                <h5 class="card-title"> Zápis absencie</h5>
              </div>
              <div class="w-100">
                <p class="card-text">Kliknite na zapísanie absencie študentom.</p>
              </div>
            </div>
          </div>
        </a>
      </div>
      <div class="col-md-6 col-sm-12 mt-20" data-aos="fade-up">
        <a href="/triedy/<%= current_teacher.id %>">
          <div class="card">
            <div class="card-body">
              <div class="w-20 float-left">
                <i class="fab fa-buromobelexperte big"></i>
              </div>
              <div class="w-80 float-left">
                <h5 class="card-title"> Manažment tried</h5>
              </div>
              <div class="w-100">
                <p class="card-text">Kliknite na spravovanie tried.</p>
              </div>
            </div>
          </div>
        </a>
      </div>
      <div class="col-md-6 col-sm-12 mt-20" data-aos="fade-up">
        <a href="/ucitelia">
          <div class="card">
            <div class="card-body">
              <div class="w-20 float-left">
                <i class="fas fa-users big"></i>
              </div>
              <div class="w-80 float-left">
                <h5 class="card-title"> Manažment učiteľov</h5>
              </div>
              <div class="w-100">
                <p class="card-text">Kliknite na spravovanie učiteľov.</p>
              </div>
            </div>
          </div>
        </a>
      </div>
    </div>
    <% end %>
  </div>
</div>

<div class="container">




  <div class="row">
    <div class="col-lg-6">
      <canvas id="bar" width="400" height="400"></canvas>
      <div class="hidden">
        <span class="students"><%= @pocet_studentov %></span>
        <span class="teachers"><%= @pocet_ucitelov %></span>
      </div>
    </div>
    <div class="col-lg-6">
      <canvas id="pie" width="400" height="400"></canvas>
      <div class="hidden">
        <span class="grade-1"><%= @pocet_jednotiek %></span>
        <span class="grade-2"><%= @pocet_dvojok %></span>
        <span class="grade-3"><%= @pocet_trojok %></span>
        <span class="grade-4"><%= @pocet_stvoriek %></span>
        <span class="grade-5"><%= @pocet_patiek %></span>
      </div>
    </div>
  </div>
</div>



<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"></script>
<script>
    var students_num = parseInt($(".students").text());
    var teachers_num = parseInt($(".teachers").text());
    var ctx = document.getElementById("bar").getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: ["Študenti", "Učitelia"],
            datasets: [{
                label: 'počet',
                data: [students_num, teachers_num],
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)'
                ],
                borderColor: [
                    'rgba(255,99,132,1)',
                    'rgba(54, 162, 235, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero:true
                    }
                }]
            },
            title: {
                display: true,
                text: 'Počet užívateľov v systéme'
            }
        }
    });

    var grade_1 = parseInt($(".grade-1").text()),
        grade_2 = parseInt($(".grade-2").text()),
        grade_3 = parseInt($(".grade-3").text()),
        grade_4 = parseInt($(".grade-4").text()),
        grade_5 = parseInt($(".grade-5").text()),
    ctx = document.getElementById("pie").getContext('2d');
    myChart = new Chart(ctx, {
        type: 'pie',
        data: {
            labels: ["Jednotky", "Dvojky", "Trojky", "Štvorky", "Päťky"],
            datasets: [{
                label: '# of Votes',
                data: [grade_1, grade_2, grade_3,grade_4, grade_5],
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)'
                ],
                borderColor: [
                    'rgba(255,99,132,1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            },
            title: {
                display: true,
                text: 'Počty udelených známok'
            }
        }
    });
</script>