config/routes.rb
Rails.application.routes.draw do
  devise_for :teachers
  devise_for :students
  resources :homes
  resources :absences
  resources :grades
  resources :classes
  resources :students
  resources :subjects
  resources :teachers
  resource :teacher_subjects


  root to: 'homes_#index'
  get "znamky/:stud_id", to: "students#show_all_grades"
  get "absencie/:stud_id", to: "students#show_all_absence"
  get "zapis_znamky/:teach_id", to: "teachers#show_teacher_grades", as: "znamky_ucitela"
  get "zapis_absencii/:teach_id", to: "teachers#show_all_absences", as: "vypis_absencii_ucitel"

  post "zapis_znamky/:teach_id", to: "teachers#add_grade"
  get "zapis_znamky/:teach_id/edit/:grade_id", to: "teachers#edit", as: "znamky_edit"
  post "zapis_absencii/:teach_id", to: "teachers#add_absence"
  get "zapis_absencii/:teach_id/edit/:abs_id", to: "teachers#edit_absence", as: "absencie_edit"
  delete "zapis_znamky/:teach_id", to: "grades#destroy"
  delete "zapis_absencii/:teach_id", to: "absences#destroy"
  delete "triedy/:teach_id", to: "classes#destroy"
  get "triedy/:teach_id", to: "teachers#all_classes", as: "vsetky_triedy"
  get "triedy/:teach_id/edit/:class_id", to: "teachers#edit_triedy", as: "class_edit"
  post "triedy/:teach_id", to: "teachers#add_classes"
  get "triedy/:teach_id/:class_id",  to:"teachers#class_detail", as: "class_detail"
  get "triedy/:teach_id/:class_id/edit/:stud_id", to:"teachers#edit_triedy_ziaka", as: "student_class_edit"
  get "ucitelia", to:"teachers#teachers_managment", as: "ucitelia_home"
  get "ucitelia/:id", to: "teachers#rozcestnik", as: "rozcestnik_pre_ucitelov"
  get "ucitelia/:id/predmety", to: "teachers#ucitel_predmety", as: "ucitel_predmety"
  get "ucitelia/:id/triedy", to: "teachers#ucitel_triedy", as: "ucitel_triedy"
  post "ucitelia/:id/predmety", to: "teachers#add_subject_teacher", as: "ucitel_add_triedy"
  get "vysvedcenie/:student_id/", to:"teachers#download_report"
  delete "ucitelia/:id/predmety", to: "teachers#destroy_teacher_subject"
  delete "ucitelia/:id/triedy", to: "teachers#destroy_teacher_classe"
  post "ucitelia/:id/triedy", to: "teachers#add_class_teacher"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subject.rb
class Subject < ApplicationRecord
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :authenticate_teacher!
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all.to_a.paginate(:page => params[:page], :per_page => 20)
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:name, :difficulty, :credits)
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_with(model: subject, local: true) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :Názov %>
    <%= form.text_field :name, id: :subject_name, :class => 'form-control'  %>
  </div>

  <div class="form-group">
    <%= form.label :Obtiažnosť %>
    <%= form.number_field :difficulty, id: :subject_difficulty, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :Počet_kreditov %>
    <%= form.number_field :credits, id: :subject_credits, :class => 'form-control'  %>
  </div>

  <div class="actions">
    <%= form.submit "Ulož predmet", :class => 'btn btn-red' %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<div class="jumbotron jumbotron-fluid bg-light">
  <div class="container">
    <h1 class="display-4">Pridať nový predmet <%= link_to 'Naspäť na prehľad predmetov', subjects_path, :class => "btn btn-red btn-lg float-right" %></h1>
  </div>
</div>

<div class="container">
  <%= render 'form', subject: @subject %>
</div>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-lg-4 pt-3 pl-5 pr-5 bg-light height-max">
    <h1 class="display-4" data-aos="fade-right">
      <i class="fas fa-book"></i> Manažment predmetov
    </h1>
    <p class="text-muted">Táto sekcia slúži na jednoduchú manipuláciu s predmetmi.</p>
    <hr class="my-4">

  </div>
  <div class="col-lg-8 pt-3 pr-5 height-max">
    <div style="margin-bottom: 10px; text-align: right">
      <%= link_to 'Nový predmet', new_subject_path, :class => "btn btn-red text-white" %>
      <button class="btn btn-success" id="btnExport">Exportovať</button>
    </div>
    <table class="table table-sm" id="tableWrapper" data-aos="fade-up">
      <thead class="thead-red">
      <tr>
        <th scope="col">Názov</th>
        <th scope="col">Obtiažnosť</th>
        <th scope="col">Kredity</th>
        <th scope="col" colspan="3">Akcie</th>
      </tr>
      </thead>
      <tbody>
      <% @subjects.each do |subject| %>
        <tr>
          <th scope="row"><%= subject.name %></th>
          <td><%= subject.difficulty %></td>
          <td><%= subject.credits %></td>
          <td>
            <%= link_to 'Upraviť', edit_subject_path(subject), :class => "btn btn-warning" %>
            <%= link_to 'Vymazať', subject, method: :delete, data: {confirm: 'Ste si istý?'}, :class => "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <%= will_paginate @subjects %>
  </div>
</div>

app/views/subjects/new.html.erb
<div class="jumbotron jumbotron-fluid bg-light">
  <div class="container">
    <h1 class="display-4"><i class="fas fa-plus"></i> Pridať nový predmet <%= link_to 'Naspäť na prehľad predmetov', subjects_path, :class => "btn btn-red btn-lg float-right" %></h1>
  </div>
</div>

<div class="container">
  <%= render 'form', subject: @subject %>
</div>

app/views/subjects/show.html.erb
<div class="jumbotron jumbotron-fluid bg-light">
  <div class="container">
    <h1 class="display-4">Pridať nový predmet <%= link_to 'Upraviť predmet', edit_subject_path(@subject), :class => "btn btn-warning btn-lg float-right" %> <%= link_to 'Naspäť na prehľad predmetov', subjects_path, :class => "btn btn-red btn-lg float-right" %></h1>
  </div>
</div>

<div class="container">
  <table class="table">
    <thead>
    <tr>
      <th scope="col">Názov</th>
      <th scope="col">Náročnosť</th>
      <th scope="col">Počet kreditov</th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td><%= @subject.name %></td>
      <td><%= @subject.difficulty %></td>
      <td><%= @subject.credits %></td>
    </tr>
    </tbody>
  </table>
</div>