config/routes.rb
Rails.application.routes.draw do
  devise_for :teachers
  devise_for :students
  resources :homes
  resources :absences
  resources :grades
  resources :classes
  resources :students
  resources :subjects
  resources :teachers
  resource :teacher_subjects


  root to: 'homes_#index'
  get "znamky/:stud_id", to: "students#show_all_grades"
  get "absencie/:stud_id", to: "students#show_all_absence"
  get "zapis_znamky/:teach_id", to: "teachers#show_teacher_grades", as: "znamky_ucitela"
  get "zapis_absencii/:teach_id", to: "teachers#show_all_absences", as: "vypis_absencii_ucitel"

  post "zapis_znamky/:teach_id", to: "teachers#add_grade"
  get "zapis_znamky/:teach_id/edit/:grade_id", to: "teachers#edit", as: "znamky_edit"
  post "zapis_absencii/:teach_id", to: "teachers#add_absence"
  get "zapis_absencii/:teach_id/edit/:abs_id", to: "teachers#edit_absence", as: "absencie_edit"
  delete "zapis_znamky/:teach_id", to: "grades#destroy"
  delete "zapis_absencii/:teach_id", to: "absences#destroy"
  delete "triedy/:teach_id", to: "classes#destroy"
  get "triedy/:teach_id", to: "teachers#all_classes", as: "vsetky_triedy"
  get "triedy/:teach_id/edit/:class_id", to: "teachers#edit_triedy", as: "class_edit"
  post "triedy/:teach_id", to: "teachers#add_classes"
  get "triedy/:teach_id/:class_id",  to:"teachers#class_detail", as: "class_detail"
  get "triedy/:teach_id/:class_id/edit/:stud_id", to:"teachers#edit_triedy_ziaka", as: "student_class_edit"
  get "ucitelia", to:"teachers#teachers_managment", as: "ucitelia_home"
  get "ucitelia/:id", to: "teachers#rozcestnik", as: "rozcestnik_pre_ucitelov"
  get "ucitelia/:id/predmety", to: "teachers#ucitel_predmety", as: "ucitel_predmety"
  get "ucitelia/:id/triedy", to: "teachers#ucitel_triedy", as: "ucitel_triedy"
  post "ucitelia/:id/predmety", to: "teachers#add_subject_teacher", as: "ucitel_add_triedy"
  get "vysvedcenie/:student_id/", to:"teachers#download_report"
  delete "ucitelia/:id/predmety", to: "teachers#destroy_teacher_subject"
  delete "ucitelia/:id/triedy", to: "teachers#destroy_teacher_classe"
  post "ucitelia/:id/triedy", to: "teachers#add_class_teacher"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



end

app/controllers/teacher/confirmations_controller.rb
# frozen_string_literal: true

class Teacher::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/teacher/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Teacher::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/teacher/passwords_controller.rb
# frozen_string_literal: true

class Teacher::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/teacher/registrations_controller.rb
# frozen_string_literal: true

class Teacher::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/teacher/sessions_controller.rb
# frozen_string_literal: true

class Teacher::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/teacher/unlocks_controller.rb
# frozen_string_literal: true

class Teacher::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :authenticate_teacher!
  require 'will_paginate'
  #zobraz známky udelené konkrétnym učiteľom
  def show_teacher_grades

    id_ucitela = params[:teach_id]
    if (id_ucitela.to_i == current_teacher.id)
      @all_grades=ActiveRecord::Base.connection.execute("

      SELECT grades.id as grade_id,s2.name as stname ,c2.name as trname, s3.name as prname ,grades.value as znamka, grades.created_at as datum,grades.students_id as students_id, grades.subjects_id as subjects_id, grades.value FROM grades
        JOIN students s2 ON grades.students_id = s2.id
        JOIN subjects s3 ON grades.subjects_id = s3.id
        JOIN teacher_subjects s4 ON s3.id = s4.subjects_id
        JOIN teachers t ON s4.teachers_id = t.id
        JOIN classes c2 ON s2.classes_id = c2.id
      WHERE (t.id=" + id_ucitela + ")
      ").to_a.paginate(:page => params[:page], :per_page => 20)

      @all_classes = ActiveRecord::Base.connection.execute("SELECT id, name FROM classes")
      @all_students = ActiveRecord::Base.connection.execute("SELECT id, name FROM students")
    end

  end
#zobraz absencie udelené konkrétnym učiteľom
  def show_all_absences
    id_ucitela = params[:teach_id]
    if(id_ucitela.to_i == current_teacher.id)
      @all_absences = ActiveRecord::Base.connection.execute(
          "SELECT absences.id as absence_id, s.name as stname, c.name as trname, absences.when as datum, absences.reason as dovod, absences.created_at as datum_dorucenia FROM absences
            JOIN students s ON absences.students_id = s.id
            JOIN classes c ON s.classes_id = c.id
          ").to_a.paginate(:page => params[:page], :per_page => 20)
      @all_classes = ActiveRecord::Base.connection.execute("SELECT id, name FROM classes")
      @all_students = ActiveRecord::Base.connection.execute("SELECT id, name FROM students")
    end
  end
#pridaj absenciu
  def add_absence
    @absence = Absence.new(absence_params)

    respond_to do |format|
      if @absence.save
        format.html {redirect_to vypis_absencii_ucitel_path, notice: 'Absencia úspešne pridaná'}
      else
        format.html {render :pridaj}
        format.json {render json: @grade.errors, status: :unprocessable_entity}
      end
    end
  end
#pridaj známku
  def add_grade
    @grade = Grade.new(grade_params)

    respond_to do |format|
      if @grade.save
        format.html {redirect_to znamky_ucitela_path, notice: 'Známka úspešne pridaná'}
        #format.json {render :show, status: :created, location: @grade}
      else
        format.html {render :pridaj}
        format.json {render json: @grade.errors, status: :unprocessable_entity}
      end
    end
  end
  #pridaj triedu
  def add_classes
    @triedy =Classe.new(classes_params)

    respond_to do |format|
      if @triedy.save
        format.html {redirect_to vsetky_triedy_path, notice: 'Trieda úspešne pridaná'}
        #format.json {render :show, status: :created, location: @grade}
      else
        format.html {render :pridaj}
        format.json {render json: @grade.errors, status: :unprocessable_entity}
      end
    end
  end

  def edit
    @grade = Grade.find(params[:grade_id])
  end

  def edit_absence
    @absence = Absence.find(params[:abs_id])
  end

  def edit_triedy
    @triedy = Classe.find(params[:class_id])
  end

  def edit_triedy_ziaka
    @student = Student.find(params[:stud_id])
  end

  def edit_ucitel_predmet
    @teacher_subjects = TeacherSubject.find(params[:id])
  end
#zobraz všetky triedy
  def all_classes
    id_ucitela = params[:teach_id]
    if(id_ucitela.to_i == current_teacher.id)
      @all_classes = ActiveRecord::Base.connection.execute(
          "SELECT classes.id, classes.name, COUNT(students.name) FROM classes
           JOIN students ON classes.id = students.classes_id
           GROUP BY classes.name, classes.id"
      )
    end
  end
#zobraz žiakov danej triedy
  def class_detail
    id_ucitela = params[:teach_id]
    id_triedy = params[:class_id].to_s
    if(id_ucitela.to_i == current_teacher.id)
      @detail = ActiveRecord::Base.connection.execute("
      SELECT s2.id as sid,s2.name as stname,classes.name as trname, s2.birth_date as bdate, s2.email as email, s2.last_sign_in_at as nprihlaseny  FROM classes
      join students s2 ON classes.id = s2.classes_id
      where (classes.id = "+id_triedy+")
      ")
    end
  end


  def teachers_managment
    @teachers = ActiveRecord::Base.connection.execute("SELECT * FROM teachers")
  end

  def rozcestnik
  end
#zobraz predmety daneho ucitela
  def ucitel_predmety
    @predmety = ActiveRecord::Base.connection.execute("
    SELECT teachers.id as tid,s2.name as prname,s2.difficulty as obt,s2.credits as pkreditov,subject.id as sid  FROM teachers
    JOIN teacher_subjects subject ON teachers.id = subject.teachers_id
    JOIN subjects s2 ON subject.subjects_id = s2.id
    WHERE (teachers.id = "+params[:id].to_s+")
")
  end
#zobraz triedy daneho ucitela
  def ucitel_triedy
    @teacher_classe= ActiveRecord::Base.connection.execute("
    SELECT c2.name as trname, tc.id as tcid FROM teachers
    JOIN teacher_classes tc ON teachers.id = tc.teachers_id
    JOIN classes c2 ON tc.classes_id = c2.id
    WHERE (teachers.id = "+params[:id].to_s+")
    ")
  end

  #pridaj predmet učitelovi
  def add_subject_teacher
    @tes =TeacherSubject.new(tes_params)

    respond_to do |format|
      if @tes.save
        format.html {redirect_to ucitel_predmety_path, notice: 'Predmet úspešne pridaná'}
        #format.json {render :show, status: :created, location: @grade}
      else
        format.html {render :ucitel_predmety}
        format.json {render json: @tes.errors, status: :unprocessable_entity}
      end
    end
  end
#stiahni vysvedčenie
  def download_report
    id_ziaka = params[:student_id].to_s
    @info = ActiveRecord::Base.connection.execute(
        "SELECT students.name stname, students.birth_date, res.* FROM students JOIN
          (SELECT subjects.name, grades.students_id, ROUND(avg(grades.value), 0) FROM subjects JOIN grades ON grades.subjects_id = subjects.id
          GROUP BY subjects.name, grades.students_id) res ON students.id = res.students_id
          WHERE students_id = "+id_ziaka)

  end
#zmaž predmet učitelovi
  def destroy_teacher_subject
    @teacher_subject=TeacherSubject.find(params[:sid])
    TeacherSubject.transaction do
      @teacher_subject.destroy
      respond_to do |format|
        format.html { redirect_to ucitel_predmety_path, notice: 'Známka zmazaná' }
        format.json { head :no_content }
      end
    end
  end
#zmaž triedu učitelov
  def destroy_teacher_classe
    @teacher_classe=TeacherClasse.find(params[:tcid])
    TeacherClasse.transaction do
      @teacher_classe.destroy
      respond_to do |format|
        format.html { redirect_to ucitel_triedy_path, notice: 'Známka zmazaná' }
        format.json { head :no_content }
      end
    end
  end
#pridaj triedu ucitelovi
  def add_class_teacher
    @teacher_classe =TeacherClasse.new(teacher_class_params)

    respond_to do |format|
      if @teacher_classe.save
        format.html {redirect_to ucitel_triedy_path, notice: 'Trieda úspešne pridaná'}
        #format.json {render :show, status: :created, location: @grade}
      else
        format.html {render :ucitel_triedy}
        format.json {render json: @tes.errors, status: :unprocessable_entity}
      end
    end
  end

  private
  def grade_params
    params.require(:grade).permit(:value, :students_id, :subjects_id)
  end
  def absence_params
    params.require(:absence).permit(:when, :reason, :students_id)
  end
  def classes_params
    params.require(:triedy).permit(:name)
  end
  def tes_params
    params.require(:teacher_subject).permit(:teachers_id,:subjects_id)
  end
  def teacher_class_params
    params.require(:teach_subject).permit(:teachers_id,:classes_id)
  end

end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_absences_form.html.erb
<% if @absence == NIL %>
  <%= form_for(:absence, local: true) do |form| %>

    <div class="row">
      <div class="col-lg-6">
        <div class="form-group">
          <%= form.label :Žiak %>
          <%= form.collection_select(:students_id, Student.all, :id, :name, {:prompt => 'Vyber žiaka'}, {class: 'form-control'}) %>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="form-group custom">
          <%= form.label :Dátum, :class => 'display-block' %>
          <%= form.date_select(:when, id: :announcement_date, :class => 'form-control') %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :Dôvod %>
      <%= form.text_field :reason, :class => 'form-control' %>

    </div>

    <div class="actions">
      <%= form.submit "Ulož absenciu", :class => 'btn btn-red' %>
    </div>
  <% end %>

<% else %>
  <%= form_for(@absence, local: true) do |form| %>

    <div class="row">
      <div class="col-lg-6">
        <div class="form-group">
          <%= form.label :Žiak %>
          <%= form.collection_select(:students_id, Student.all, :id, :name, {:prompt => 'Vyber žiaka'}, {class: 'form-control'}) %>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="form-group">
          <%= form.label :Dátum %>
          <%= form.date_select(:when, id: :announcement_date) %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :Dôvod %>
      <%= form.text_field :reason, :class => 'form-control' %>

    </div>

    <div class="actions">
      <%= form.submit "Ulož absenciu", :class => 'btn btn-red'%>
    </div>
  <% end %>
<% end %>

app/views/teachers/all_classes.html.erb
<% if @all_classes == NIL %>
  <h3 class="alert alert-danger">Nie sú zadané žiadne absencie.</h3>
<% else %>
  <div class="jumbotron jumbotron-fluid bg-light">
    <div class="container">
      <h1 class="display-4"><i class="fab fa-buromobelexperte big"></i> Manažment tried</h1>
      <p class="lead">Táto sekcia slúži na jednoduchú manipuláciu a administráciu tried.</p>
      <hr class="my-4">
      <%= render 'triedy_form', grade: @triedy %>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <% count = 1 %>
      <% @all_classes.each do |triedy| %>

        <% if count % 2 == 1 %>
          <div class="col-md-6 col-sm-12 mt-20" data-aos="fade-right" data-aos-delay="<%= count * 50 %>">
        <% else %>
          <div class="col-md-6 col-sm-12 mt-20" data-aos="fade-left" data-aos-delay="<%= count * 50 %>">
        <% end %>
        <% count += 1 %>
            <div class="card">
              <div class="card-body">
                <div class="w-20 float-left text-dark">
                  <span class="big"><%= triedy.fetch('name') %></span>
                </div>
                <% triedy[:class_id] = triedy.fetch('id').to_i %>
                <% triedy[:id] = triedy.fetch('id').to_i %>
                <div class="w-80 float-left">
                  <h5 class="card-title text-dark float-right">Počet žiakov v triede: <strong><%= triedy.fetch('count') %></strong></h5>
                </div>
                <div class="w-100">
                  <p class="card-text float-right">
                    <% %>
                    <%= link_to 'Detail',class_detail_path(triedy),class: "btn btn-outline-info" %>
                    <%= link_to 'Upraviť',class_edit_path(triedy),class: "btn btn-outline-warning" %>
                    <%= link_to 'Vymazať', triedy, method: :delete, data: { confirm: 'Ste si istý?' },class: "btn btn-outline-danger" %>
                  </p>
                </div>
              </div>
            </div>
        </div>
      <% end %>
    </div>
  </div>
  </div>
<% end %>

app/views/teachers/class_detail.html.erb
<% if @detail == NIL %>
  <h3 class="alert alert-danger">V tejto triedie nie sú žiadny žiaci.</h3>
<% else %>

  <div class="jumbotron jumbotron-fluid bg-light">
    <div class="container">
      <h1 class="display-4"><i class="fab fa-buromobelexperte big"></i> Detail triedy <%= params[:name] %>
        <a href="/triedy/<%= current_teacher.id %>" class="btn btn-red btn-lg float-right"><i class="fas fa-chevron-left"></i> Naspäť na prehľad tried</a>
      </h1>
      <hr class="my-4">
    </div>
  </div>

  <div class="container">
    <div class="row">
      <% count = 1 %>
      <div class="card-deck mb-3">
      <% @detail.each do |details| %>
          <div class="card text-dark bg-light mb-3" style="max-width: 18rem;" data-aos="fade-up" data-aos-delay="<%= count * 50 %>">
          <% count += 1 %>
            <% details[:stud_id] = details.fetch('sid').to_i %>
            <div class="card-header">Študent<%= link_to 'Edit', student_class_edit_path(details), class: "btn btn-outline-warning float-right" %></div>
            <div class="card-body">
              <h5 class="card-title">
                <%= details.fetch('stname') %>
                <span class="float-right"><%= details.fetch('trname') %></span>
              </h5>
              <hr>
              <ul>
                <li><%= details.fetch('email') %></li>
                <li>
                  <strong>Dátum narodenia:</strong><br>
                  <%= details.fetch('bdate') %>
                </li>
                <li>
                  <strong>Naposledny prihlásený:</strong><br>
                  <%= DateTime.parse(details.fetch('nprihlaseny')).strftime('%a %b %d %H:%M:%S %Y') %>
                </li>
                <li><a href="/vysvedcenie/<%= details.fetch('sid') %>" class="btn btn-link">Stiahnuť vysvedčenie</a></li>
              </ul>
            </div>
          </div>
      <% end %>
      </div>
      </div>
    </div>
  </div>
<% end %>

app/views/teachers/edit_triedy.html.erb
<h2 class="text-center display-4">Upraviť triedu <%= params[:name] %></h2>
<div class="wrapper-center w-50">
  <%= render 'triedy_form', triedy: @triedy %>
</div>

app/views/teachers/edit_ucitel_predmet.erb
<h2 class="text-center display-4">Upraviť Predmet</h2>
<div class="wrapper-center w-50">
  <%= render 'edit_teacher_predmet', teacher_subject: @teacher_subject %>
</div>

app/views/teachers/show_all_absences.html.erb
<% if @all_absences == NIL %>
  <h3 class="alert alert-danger">Nie sú zadané žiadne absencie.</h3>
<% else %>
  <div class="row">
    <div class="col-lg-4 pt-3 pl-5 pr-5 bg-light height-max">
      <h1 class="display-4">
        Prehľad absencií žiakov
      </h1>
      <p class="text-muted">Prehľad absencií jednotlivých žiakov.</p>
      <hr>

      <h6>Pridať absenciu</h6>
      <%= render 'absences_form', grade: @absence %>

    </div>
    <div class="col-lg-8 pt-3 pr-5 height-max">
      <div style="margin-bottom: 10px; text-align: right">
        <button class="btn btn-success" id="btnExport">Exportovať</button>
      </div>
      <table class="table table-sm" id="tableWrapper">
        <thead class="thead-red">
        <tr>
          <th scope="col">Žiak</th>
          <th scope="col">Trieda</th>
          <th scope="col">Dátum absencie</th>
          <th scope="col">Dôvod</th>
          <th scope="col">Dátum doručenia</th>
          <th scope="col" colspan="2">Akcie</th>
        </tr>
        </thead>
        <tbody>
        <% @all_absences.each do |absencie| %>
          <tr>
            <th scope="row"><%= absencie.fetch('stname') %></th>
            <td><%= absencie.fetch('trname') %></td>
            <td><%= absencie.fetch('datum') %></td>
            <td><%= absencie.fetch('dovod') %></td>
            <td><%= DateTime.parse(absencie.fetch('datum_dorucenia')).strftime('%a %b %d %H:%M:%S %Y') %></td>
            <%absencie[:abs_id]=absencie.fetch('absence_id').to_i%>
            <td><%= link_to 'Edit',absencie_edit_path(absencie),class: "btn btn-warning" %></td>
            <td><%= link_to 'Vymazať', absencie, method: :delete, data: { confirm: 'Ste si istý?' },class: "btn btn-danger" %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <%= will_paginate @all_absences %>
    </div>
  </div>
<% end %>

app/views/teachers/show_teacher_grades.html.erb
<% if @all_grades == NIL %>
  <h3 class="alert alert-danger">Permission Denied: pristupujete ku známkam iného žiaka.</h3>
<% else %>
  <div class="row">
    <div class="col-lg-4 pt-3 pl-5 pr-5 bg-light height-max">
      <h1 class="display-4">
        Výpis udeľených známok
      </h1>
      <p class="text-muted">Prehľad známok jednotlivých predmetov.</p>
      <hr>
      <h6>Pridaj známku</h6>

      <%= render 'add_grade_form', grade: @all_grades %>

      <hr>
    </div>
    <div class="col-lg-8 pt-3 pr-5 height-max">
      <div style="margin-bottom: 10px; text-align: right">
        <button class="btn btn-success" id="btnExport">Exportovať</button>
      </div>
      <table class="table table-sm" id="tableWrapper">
        <thead class="thead-red">
        <tr>
          <th scope="col">Žiak</th>
          <th scope="col">Trieda</th>
          <th scope="col">Predmet</th>
          <th scope="col">Znamka</th>
          <th scope="col">Dátum</th>
          <th scope="col" colspan="2">Akcia</th>
        </tr>
        </thead>
        <tbody>
        <% @all_grades.each do |znamky| %>
          <tr>
            <th scope="row"><%= znamky.fetch('stname') %></th>
            <td><%= znamky.fetch('trname') %></td>
            <td><%= znamky.fetch('prname') %></td>
            <td><%= znamky.fetch('znamka') %></td>
            <td><%= DateTime.parse(znamky.fetch('datum')).strftime('%a %b %d %H:%M:%S %Y') %></td>
            <%znamky[:grade_id]=znamky.fetch('grade_id').to_i%>
            <td><%= link_to 'Upraviť',znamky_edit_path(znamky),class: "btn btn-warning" %></td>
            <td><%= link_to 'Vymazať', znamky, method: :delete, data: { confirm: 'Ste si istý?' },class: "btn btn-danger" %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <%= will_paginate @all_grades %>
    </div>
  </div>

<% end %>

app/views/teachers/teachers_managment.html.erb
<% if @teachers == NIL %>
  <h3 class="alert alert-danger">Nemáte v syst=eme žiadnych učiteľov.</h3>
<% else %>

  <div class="jumbotron jumbotron-fluid bg-light">
    <div class="container">
      <h1 class="display-4"><i class="fas fa-users big"></i></i> Manažment učiteľov
      </h1>
      <hr class="my-4">
      <p class="lead">Táto sekcia slúži na jednoduchú manipuláciu a administráciu učiteľov - ich predmetov a tried.</p>

    </div>
  </div>

  <div class="container">
    <div class="row">
      <% count = 1 %>
      <div class="card-deck mb-3">
        <% @teachers.each do |ucitelia| %>
          <div class="card text-dark bg-light mb-3" style="max-width: 18rem;" data-aos="fade-up" data-aos-delay="<%= count * 50 %>">
            <% count += 1 %>
            <% ucitelia[:id]=ucitelia.fetch('id').to_i%>
            <div class="card-header">Učiteľ<%= link_to 'Upraviť',rozcestnik_pre_ucitelov_path(ucitelia),class: "btn btn-outline-warning float-right" %></div>
            <div class="card-body">
              <h5 class="card-title">
                <%= ucitelia.fetch('name') %>
              </h5>
              <hr>
              <ul>
                <li><%= ucitelia.fetch('email') %></li>
                <li><%= ucitelia.fetch('birth_date') %></li>
                <li><%= DateTime.parse(ucitelia.fetch('last_sign_in_at')).strftime('%a %b %d %H:%M:%S %Y') %></li>
                <li><%= ucitelia.fetch('credit_number') %></li>
                </li>
              </ul>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  </div>
<% end %>