config/routes.rb
Rails.application.routes.draw do
  devise_for :teachers
  devise_for :students
  resources :homes
  resources :absences
  resources :grades
  resources :classes
  resources :students
  resources :subjects
  resources :teachers
  resource :teacher_subjects


  root to: 'homes_#index'
  get "znamky/:stud_id", to: "students#show_all_grades"
  get "absencie/:stud_id", to: "students#show_all_absence"
  get "zapis_znamky/:teach_id", to: "teachers#show_teacher_grades", as: "znamky_ucitela"
  get "zapis_absencii/:teach_id", to: "teachers#show_all_absences", as: "vypis_absencii_ucitel"

  post "zapis_znamky/:teach_id", to: "teachers#add_grade"
  get "zapis_znamky/:teach_id/edit/:grade_id", to: "teachers#edit", as: "znamky_edit"
  post "zapis_absencii/:teach_id", to: "teachers#add_absence"
  get "zapis_absencii/:teach_id/edit/:abs_id", to: "teachers#edit_absence", as: "absencie_edit"
  delete "zapis_znamky/:teach_id", to: "grades#destroy"
  delete "zapis_absencii/:teach_id", to: "absences#destroy"
  delete "triedy/:teach_id", to: "classes#destroy"
  get "triedy/:teach_id", to: "teachers#all_classes", as: "vsetky_triedy"
  get "triedy/:teach_id/edit/:class_id", to: "teachers#edit_triedy", as: "class_edit"
  post "triedy/:teach_id", to: "teachers#add_classes"
  get "triedy/:teach_id/:class_id",  to:"teachers#class_detail", as: "class_detail"
  get "triedy/:teach_id/:class_id/edit/:stud_id", to:"teachers#edit_triedy_ziaka", as: "student_class_edit"
  get "ucitelia", to:"teachers#teachers_managment", as: "ucitelia_home"
  get "ucitelia/:id", to: "teachers#rozcestnik", as: "rozcestnik_pre_ucitelov"
  get "ucitelia/:id/predmety", to: "teachers#ucitel_predmety", as: "ucitel_predmety"
  get "ucitelia/:id/triedy", to: "teachers#ucitel_triedy", as: "ucitel_triedy"
  post "ucitelia/:id/predmety", to: "teachers#add_subject_teacher", as: "ucitel_add_triedy"
  get "vysvedcenie/:student_id/", to:"teachers#download_report"
  delete "ucitelia/:id/predmety", to: "teachers#destroy_teacher_subject"
  delete "ucitelia/:id/triedy", to: "teachers#destroy_teacher_classe"
  post "ucitelia/:id/triedy", to: "teachers#add_class_teacher"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/absence.rb
class Absence < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/classe.rb
class Classe < ApplicationRecord
end

app/models/grade.rb
class Grade < ApplicationRecord


end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/models/subject.rb
class Subject < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



end

app/models/teacher_classe.rb
class TeacherClasse < ApplicationRecord
end

app/models/teacher_subject.rb
class TeacherSubject < ApplicationRecord
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController

def show

end
#edit známky
  def update
    @grade=Grade.find(params[:id])
    respond_to do |format|
      if @grade.update(grade_params)
        format.html { redirect_to "/zapis_znamky/"+current_teacher.id.to_s+"", notice: 'Známka úspešne upravená' }
        #format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end
#zmazanie známky
def destroy
  Grade.transaction do
    @grade=Grade.find(params[:grade_id])
    @grade.destroy
    respond_to do |format|
      format.html { redirect_to "/zapis_znamky/"+current_teacher.id.to_s+"", notice: 'Známka zmazaná' }
      format.json { head :no_content }
    end
  end
end

  private
  def grade_params
    params.require(:grade).permit(:value, :students_id, :subjects_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    before_action :authenticate_student!, except: [ :index]
    before_action :authenticate_teacher!, except: [ :index]
#Priprava udajov pre grafy na landing page
  def index
    @pocet_ucitelov = Teacher.all.count
    @pocet_studentov = Student.all.count
    @pocet_jednotiek = Grade.all.where(value: 1).count
    @pocet_dvojok = Grade.all.where(value: 2).count
    @pocet_trojok = Grade.all.where(value: 3).count
    @pocet_stvoriek = Grade.all.where(value: 4).count
    @pocet_patiek = Grade.all.where(value: 5).count
  end
end

app/helpers/absences_helper.rb
module AbsencesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classes_helper.rb
module ClassesHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VAVAEducationSystem2018</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">
    <link href="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css" rel="stylesheet">
  </head>

  <body>
    <!-- NAVBAR START -->

    <nav class="navbar navbar-expand-lg navbar-dark bg-red">
      <a class="navbar-brand" href="/"><i class="fas fa-graduation-cap"></i> R&A EDU</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <% if (student_signed_in?)  %>
          <li class="nav-item">
            <a class="nav-link" href="/">Domov</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/znamky/<%= current_student.id %>">Známky</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/absencie/<%= current_student.id %>">Absencie</a>
          </li>
          <% end %>
          <% if (teacher_signed_in?)  %>
            <li class="nav-item"><a class="nav-link" href="/">Domov</a></li>
            <li class="nav-item"><a class="nav-link" href="/zapis_znamky/<%= current_teacher.id %>">Zápis známok</a></li>
            <li class="nav-item"><a class="nav-link" href="/zapis_absencii/<%= current_teacher.id %>">Zápis absencie</a></li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Manažment
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="/triedy/<%= current_teacher.id %>">Manažment tried</a>
                <a class="dropdown-item" href="/ucitelia">Manažment učiteľov</a>
                <a class="dropdown-item" href="/subjects">Manažment predmetov</a>
              </div>
            </li>
          <% end %>
        </ul>
        <ul class="navbar-nav">
          <% if student_signed_in? %>
            <li class="nav-item"><%= link_to 'Upraviť profil', edit_student_registration_path, :class => 'nav-link' %></li>
            <li class="nav-item"><%= link_to "Odhlásiť sa", destroy_student_session_path, method: :delete, :class => 'nav-link' %></li>
          <% end %>
          <% if !((student_signed_in?) || (teacher_signed_in?)) %>
            <li class="nav-item"><%= link_to "Registrácia", new_student_registration_path, :class => 'nav-link' %></li>
            <li class="nav-item"><%= link_to "Prihlásenie", new_student_session_path, :class => 'nav-link' %></li>
          <% end %>
          <% if teacher_signed_in? %>
            <li class="nav-item"><%= link_to 'Upraviť profil', edit_teacher_registration_path, :class => 'nav-link' %></li>
            <li class="nav-item"><%= link_to "Odhlásiť sa", destroy_teacher_session_path, method: :delete, :class => 'nav-link' %></li>
          <% end %>
          <% if (student_signed_in?) || (teacher_signed_in?) %>
            <li><div class="vertical-separator"></div></li>
          <% end %>
        </ul>
        <span class="navbar-text">

          <% if teacher_signed_in? %>
            Prihlásený ako:
            učiteľ
             <strong><%= current_teacher.email %></strong>.
          <% end %>
          <% if student_signed_in? %>
            Prihlásený ako:
            žiak
             <strong><%= current_student.email %></strong>.
          <% end %>

        </span>
      </div>
    </nav>

    <!-- NAVBAR END-->

    <% if notice %>
      <div class="alert alert-success alert-dismissible fade show alert-custom" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger alert-dismissible fade show alert-custom" role="alert">
        <%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <div class="main">
      <%= yield %>
    </div>

    <footer class="my-5 pt-5 text-muted text-center text-small">
      <p class="mb-1">© 2017-2018 Richard Križan & Adrián Vyskoč </p>
      <p class="lead">Vývoj aplikácií s viacvrstvovou architektúrou</p>
        <div class="selectpicker" id="google_translate_element"></div>
        <script type="text/javascript">
            var g_gTranslateIsAdded = false;

            function googleTranslateElementInit() {
                if (!g_gTranslateIsAdded) {
                    g_gTranslateIsAdded = true;
                    new google.translate.TranslateElement({
                        pageLanguage: 'sk',
                        layout: google.translate.TranslateElement.InlineLayout.VERTICAL,
                        autoDisplay: false
                    }, 'google_translate_element');
                }
            }
        </script>
        <script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
    </footer>
    <script src="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js"></script>
    <script>
        AOS.init();
    </script>
  </body>
</html>